---
- name: Ensure script directory exists.
  file: path="{{ mysql_backup_dir }}" state=directory

- name: Copy backup script to target destination.
  copy: src=files/backup.sh dest={{ mysql_backup_dir }}/backup.sh mode="u+x"

- name: Copy config template.
  template: src=templates/backup.cfg.j2 dest={{ mysql_backup_dir }}/backup.cfg

- name: Append MAILTO var to cron file.
  cronvar:
    name: "MAILTO"
    value: "{{ mysql_backup_cron_email }}"
    user: "root"
    cron_file: "{{ mysql_backup_cronfile }}"
  when: mysql_backup_cron_enabled and mysql_backup_cron_email

- name: Add backup script to cron.
  cron:
    name: mysql-s3-backup
    minute: "{{ mysql_backup_cron_minute }}"
    hour: "{{ mysql_backup_cron_hour }}"
    job: "{{ mysql_backup_dir }}/backup.sh --no-colors"
    user: "root"
    cron_file: "{{ mysql_backup_cronfile }}"
  when: mysql_backup_cron_enabled
